teamif: team0
slave1: ens3
slave2: ens4

vlans: true

default_conn:
  - conn_name: enp0s3
  - conn_name: "Wired connection 1"
  - conn_name: "Wired connection 2"
  - conn_name: "Wired connection 3"
  - conn_name: "Wired connection 4"

nmcli_team:
  - conn_name: '{{ teamif }}'
    ifname: '{{ teamif }}'
    method4: manual
    ip4: '{{ teamip }}'
    gw4: '{{ teamgw }}'
    method6: disabled
    runner: activebackup

nmcli_team_slave:
  - conn_name: slave1
    ifname: '{{ slave1 }}'
    master: '{{ teamif }}'
  - conn_name: slave2
    ifname: '{{ slave2 }}'
    master: '{{ teamif }}'
